apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: mdm-prod
type: Opaque
stringData:
  DATABASE_URL: postgresql://mdmpostgres:mdmpostgres@mdm-postgres:5432/mdmDB
  REDIS_URL: redis://mdm-redis:6379
  JWT_SECRET: supersecret
