apiVersion: v1
kind: Service
metadata:
  name: mdm-backend
  namespace: mdm-prod
spec:
  selector:
    app: mdm-backend
  ports:
    - port: 8000
      targetPort: 8000


# apiVersion: v1
# kind: Service
# metadata:
#   name: mdm-backend
#   namespace: mdm-prod
# spec:
#   selector:
#     app: mdm-backend
#     version: blue   # ðŸ”¥ change this to green when ready
#   ports:
#     - port: 8000
#       targetPort: 8000
