apiVersion: v1
kind: Service
metadata:
  name: mdm-frontend
  namespace: mdm-prod
spec:
  type: NodePort
  selector:
    app: mdm-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
