# name: CI – Feature Branch

# on:
#   push:
#     branches:
#       - "feature/*"
#   pull_request:
#     branches:
#       - develop

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       # -------- Backend --------
#       - name: Install backend deps
#         working-directory: backend
#         run: npm ci

#       - name: Lint backend
#         working-directory: backend
#         run: npm run lint --if-present

#       - name: Test backend
#         working-directory: backend
#         run: npm test --if-present

#       # -------- Frontend --------
#       - name: Install frontend deps
#         working-directory: frontend
#         run: npm ci

#       - name: Lint frontend
#         working-directory: frontend
#         run: npm run lint --if-present

#       - name: Test frontend
#         working-directory: frontend
#         run: npm test --if-present

#  # feature/* → lint + test