# name: Build & Deploy MDM (Develops)

# on:
#   push:
#     branches:
#       - develop   # ðŸ”¥ CHANGED FROM main â†’ develop

# env:
#   BACKEND_IMAGE: tyash26/backend
#   FRONTEND_IMAGE: tyash26/frontend

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set image tag
#         run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

#       # -------------------------
#       # Login to Docker Hub
#       # -------------------------
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       # -------------------------
#       # Build & Push Backend
#       # -------------------------
#       - name: Build backend image
#         run: |
#           docker build \
#             -t $BACKEND_IMAGE:latest \
#             -t $BACKEND_IMAGE:${IMAGE_TAG} \
#             ./backend

#       - name: Push backend image
#         run: |
#           docker push $BACKEND_IMAGE:latest
#           docker push $BACKEND_IMAGE:${IMAGE_TAG}

#       # -------------------------
#       # Build & Push Frontend
#       # -------------------------
#       - name: Build frontend image
#         run: |
#           docker build \
#             --build-arg NEXT_PUBLIC_API_URL=http://${{ secrets.SERVER_HOST }}:8000/api \
#             --build-arg NEXT_PUBLIC_SOCKET_URL=http://${{ secrets.SERVER_HOST }}:8000 \
#             -t $FRONTEND_IMAGE:latest \
#             -t $FRONTEND_IMAGE:${IMAGE_TAG} \
#             ./frontend

#       - name: Push frontend image
#         run: |
#           docker push $FRONTEND_IMAGE:latest
#           docker push $FRONTEND_IMAGE:${IMAGE_TAG}


#   deploy:
#     needs: build-and-push
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy on server via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /opt/mdm   # ðŸ‘ˆ your project path on server

#             echo "ðŸ”„ Pulling latest images..."
#             docker pull tyash26/backend:latest
#             docker pull tyash26/frontend:latest

#             echo "ðŸ›‘ Stopping old containers..."
#             docker-compose down

#             echo "ðŸš€ Starting new containers..."
#             docker-compose up -d

#             echo "ðŸ§¹ Cleaning old images..."
#             docker image prune -f

# # docker exec mdm_backend npx prisma db push
# # docker exec mdm_backend node dist/prisma/seed.js

# # develop â†’ staging
